### ISSUE TITLE
Error while testing the content-web

### ISSUE THREAD

**Issue by sowsan** [Microsoft/MCW-Containers-and-DevOps#44]
Hello - 

Getting the Error while testing the content-web in Task #1 

Error
====

**$ nodejs ./server.js &**
[2] 19404
$ /home/sowmyans/content-web/node_modules/debug/src/node.js:132
        let val = process.env[key];
        ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/sowmyans/content-web/node_modules/debug/src/index.js:9:19)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

**Comment by sowsan** [comment]
updating nodejs version to latest fixed the issue.
